export const mockEmpleado = {
  id: "demo-employee-1",
  nombre: "Felipe Fontana",
  email: "felipe@blyndtek.com",
  rol: "admin",
  activo: true,
};

export const mockConfiguracionGeneral = {
  id: true,
  empresa_nombre: "Funes Exclusivos",
  empresa_razon_social: "Funes Exclusivos S.A.",
  empresa_cuit: "30-12345678-9",
  empresa_direccion: "Av. Libertador 1234, Buenos Aires",
  empresa_telefono: "+54 9 11 4444-1000",
  empresa_email: "hola@funesexclusivos.com",
  empresa_website: "https://funesexclusivos.com",
  moneda_principal: "USD",
  moneda_secundaria: "ARS",
  porcentaje_comision_default: 1,
  dias_alerta_gestoria: 7,
  dias_alerta_leads: 2,
  whatsapp_alertas_activas: true,
  catalogo_auto_publicar_stock: false,
};

export const mockEmpleados = [
  {
    id: "emp_lucas_admin",
    email: "lucas@funesexclusivos.com",
    nombre: "Lucas Ríos",
    telefono: "+54 9 11 5555-1001",
    avatar_url: null,
    rol: "admin",
    activo: true,
    cargo: "Director Comercial",
    fecha_ingreso: "2024-03-15",
    comision_default_porcentaje: 2.5,
    notas: "Admin operativo y responsable del equipo comercial.",
    created_at: "2024-03-15T09:00:00.000Z",
    updated_at: "2026-07-06T09:10:00.000Z",
  },
  {
    id: "emp_agustina_admin",
    email: "agustina@funesexclusivos.com",
    nombre: "Agustina Pérez",
    telefono: "+54 9 11 5555-1002",
    avatar_url: null,
    rol: "admin",
    activo: true,
    cargo: "Administración General",
    fecha_ingreso: "2024-05-08",
    comision_default_porcentaje: 1.8,
    notas: "Coordina backoffice, documentación y soporte interno.",
    created_at: "2024-05-08T09:15:00.000Z",
    updated_at: "2026-07-06T09:10:00.000Z",
  },
  {
    id: "emp_martin_vendedor",
    email: "martin@funesexclusivos.com",
    nombre: "Martín Roldán",
    telefono: "+54 9 11 5555-1003",
    avatar_url: null,
    rol: "vendedor",
    activo: true,
    cargo: "Vendedor Senior",
    fecha_ingreso: "2024-09-20",
    comision_default_porcentaje: 3,
    notas: "Foco en SUV premium y operaciones de contado.",
    created_at: "2024-09-20T10:00:00.000Z",
    updated_at: "2026-07-06T09:10:00.000Z",
  },
  {
    id: "emp_sofia_vendedora",
    email: "sofia@funesexclusivos.com",
    nombre: "Sofía Benítez",
    telefono: "+54 9 11 5555-1004",
    avatar_url: null,
    rol: "vendedor",
    activo: true,
    cargo: "Vendedora",
    fecha_ingreso: "2025-01-12",
    comision_default_porcentaje: 2.75,
    notas: "Atención digital y seguimiento comercial.",
    created_at: "2025-01-12T11:20:00.000Z",
    updated_at: "2026-07-06T09:10:00.000Z",
  },
  {
    id: "emp_gestor_1",
    email: "gestoria@funesexclusivos.com",
    nombre: "Nicolás Herrera",
    telefono: "+54 9 11 5555-1005",
    avatar_url: null,
    rol: "gestor",
    activo: true,
    cargo: "Gestor Administrativo",
    fecha_ingreso: "2024-11-01",
    comision_default_porcentaje: 0,
    notas: "Documentación, trámites y seguimiento de vencimientos.",
    created_at: "2024-11-01T08:30:00.000Z",
    updated_at: "2026-07-06T09:10:00.000Z",
  },
];

export const mockVehiculos = [
  {
    id: "veh_1",
    marca: "Porsche",
    modelo: "Macan",
    version: "S 2.9 V6",
    anio: 2022,
    color: "Negro",
    km: 18200,
    dominio: "AE123PQ",
    costo_adquisicion: 78000,
    costo_moneda: "USD",
    precio_venta: 94500,
    precio_moneda: "USD",
    estado: "en_stock",
    fotos: [],
    fecha_ingreso: "2026-05-14",
    created_at: "2026-05-14T10:15:00.000Z",
    catalogo_publicado: true,
    catalogo_destacado: true,
    catalogo_titulo: "Macan S lista para entrega",
    catalogo_descripcion: "SUV premium con configuración completa y mantenimiento al día.",
    catalogo_orden: 1,
  },
  {
    id: "veh_2",
    marca: "BMW",
    modelo: "X3",
    version: "xDrive30i",
    anio: 2021,
    color: "Gris Mineral",
    km: 29400,
    dominio: "AE456ST",
    costo_adquisicion: 62000000,
    costo_moneda: "ARS",
    precio_venta: 73500000,
    precio_moneda: "ARS",
    estado: "en_stock",
    fotos: [],
    fecha_ingreso: "2026-05-02",
    created_at: "2026-05-02T12:30:00.000Z",
    catalogo_publicado: true,
    catalogo_destacado: false,
    catalogo_titulo: "BMW X3 xDrive30i",
    catalogo_descripcion: "Unidad con excelente combinación de confort y tecnología.",
    catalogo_orden: 2,
  },
  {
    id: "veh_3",
    marca: "Audi",
    modelo: "Q5",
    version: "45 TFSI",
    anio: 2020,
    color: "Blanco Ibis",
    km: 38250,
    dominio: "AF789UV",
    costo_adquisicion: 56500,
    costo_moneda: "USD",
    precio_venta: 69800,
    precio_moneda: "USD",
    estado: "vendido",
    fotos: [],
    fecha_ingreso: "2026-04-20",
    created_at: "2026-04-20T09:40:00.000Z",
    catalogo_publicado: false,
    catalogo_destacado: false,
    catalogo_titulo: "Audi Q5 disponible",
    catalogo_descripcion: "Publicación suspendida hasta reingreso a stock.",
    catalogo_orden: 8,
  },
  {
    id: "veh_4",
    marca: "Land Rover",
    modelo: "Range Rover Evoque",
    version: "P250 R-Dynamic",
    anio: 2023,
    color: "Verde Santorini",
    km: 9100,
    dominio: "AG112JK",
    costo_adquisicion: 105000,
    costo_moneda: "USD",
    precio_venta: 124900,
    precio_moneda: "USD",
    estado: "en_stock",
    fotos: [],
    fecha_ingreso: "2026-06-01",
    created_at: "2026-06-01T16:10:00.000Z",
    catalogo_publicado: true,
    catalogo_destacado: true,
    catalogo_titulo: "Range Rover Evoque R-Dynamic",
    catalogo_descripcion: "Perfil premium con presencia y equipamiento destacado.",
    catalogo_orden: 3,
  },
  {
    id: "veh_5",
    marca: "Mercedes-Benz",
    modelo: "GLC 300",
    version: "4MATIC Coupe",
    anio: 2022,
    color: "Azul Nautic",
    km: 13450,
    dominio: "AG334LM",
    costo_adquisicion: 89000000,
    costo_moneda: "ARS",
    precio_venta: 104500000,
    precio_moneda: "ARS",
    estado: "en_consignacion",
    fotos: [],
    fecha_ingreso: "2026-05-26",
    created_at: "2026-05-26T11:05:00.000Z",
    catalogo_publicado: false,
    catalogo_destacado: false,
    catalogo_titulo: "GLC 300 Coupe",
    catalogo_descripcion: "Unidad reservada para publicación futura.",
    catalogo_orden: 7,
  },
  {
    id: "veh_6",
    marca: "Volkswagen",
    modelo: "Golf",
    version: "GTI",
    anio: 2019,
    color: "Rojo Tornado",
    km: 45700,
    dominio: "AH556NO",
    costo_adquisicion: 41000,
    costo_moneda: "USD",
    precio_venta: 47900,
    precio_moneda: "USD",
    estado: "vendido",
    fotos: [],
    fecha_ingreso: "2026-03-18",
    created_at: "2026-03-18T08:55:00.000Z",
    catalogo_publicado: false,
    catalogo_destacado: false,
    catalogo_titulo: "Golf GTI performance",
    catalogo_descripcion: "Vehículo dado de baja del catálogo online.",
    catalogo_orden: 9,
  },
  {
    id: "veh_7",
    marca: "Volvo",
    modelo: "XC60",
    version: "B5 Plus",
    anio: 2024,
    color: "Plata Osmium",
    km: 6800,
    dominio: "AI778QR",
    costo_adquisicion: 71000,
    costo_moneda: "USD",
    precio_venta: 84900,
    precio_moneda: "USD",
    estado: "en_stock",
    fotos: [],
    fecha_ingreso: "2026-06-08",
    created_at: "2026-06-08T13:00:00.000Z",
    catalogo_publicado: true,
    catalogo_destacado: false,
    catalogo_titulo: "Volvo XC60 B5 Plus",
    catalogo_descripcion: "SUV de uso familiar con excelente nivel de seguridad.",
    catalogo_orden: 4,
  },
  {
    id: "veh_8",
    marca: "Toyota",
    modelo: "SW4",
    version: "SRX 2.8",
    anio: 2023,
    color: "Blanco Perlado",
    km: 22100,
    dominio: "AJ990TX",
    costo_adquisicion: 69000000,
    costo_moneda: "ARS",
    precio_venta: 79200000,
    precio_moneda: "ARS",
    estado: "en_stock",
    fotos: [],
    fecha_ingreso: "2026-06-15",
    created_at: "2026-06-15T10:20:00.000Z",
    catalogo_publicado: true,
    catalogo_destacado: false,
    catalogo_titulo: "Toyota SW4 SRX",
    catalogo_descripcion: "Una de las unidades más buscadas para el catálogo.",
    catalogo_orden: 5,
  },
];

export const mockCatalogoConfig = {
  id: true,
  activo: true,
  titulo: "Funes Exclusivos",
  descripcion: "Selección premium online",
  whatsapp_contacto: "+54 9 11 5555-0000",
  instagram_url: "https://instagram.com/funesexclusivos",
  mostrar_precios: true,
  mostrar_km: true,
  mostrar_dominio: true,
};

export const mockVentas = [
  {
    id: "venta_1",
    vehiculo_id: "veh_1",
    lead_id: "lead_1",
    vendedor_id: "emp_lucas",
    fecha_venta: "2026-06-20",
    cliente_nombre: "Bruno Fernández",
    cliente_telefono: "+54 11 4111-2233",
    cliente_email: "bruno.fernandez@email.com",
    cliente_documento: "30111222",
    precio_venta: 94500,
    moneda: "USD",
    metodo_pago: "transferencia",
    estado: "registrada",
    monto_permuta: null,
    created_at: "2026-06-20T14:15:00.000Z",
    vehiculo: mockVehiculos[0],
    vendedor: {
      id: "emp_lucas",
      nombre: "Lucas Ríos",
      email: "lucas@funesexclusivos.com",
      rol: "vendedor",
    },
    lead: {
      id: "lead_1",
      nombre: "Bruno Fernández",
      telefono: "+54 11 4111-2233",
      origen: "whatsapp",
      estado: "ganado",
    },
  },
  {
    id: "venta_2",
    vehiculo_id: "veh_2",
    vendedor_id: mockEmpleado.id,
    fecha_venta: "2026-06-18",
    cliente_nombre: "Sofía Benítez",
    cliente_telefono: "+54 11 4444-7788",
    cliente_email: "sofia.benitez@email.com",
    cliente_documento: "27222333",
    precio_venta: 73500000,
    moneda: "ARS",
    metodo_pago: "efectivo",
    estado: "registrada",
    monto_permuta: null,
    created_at: "2026-06-18T11:05:00.000Z",
    vehiculo: mockVehiculos[1],
    vendedor: {
      id: mockEmpleado.id,
      nombre: mockEmpleado.nombre,
      email: mockEmpleado.email,
      rol: mockEmpleado.rol,
    },
  },
  {
    id: "venta_3",
    vehiculo_id: "veh_3",
    vendedor_id: mockEmpleado.id,
    fecha_venta: "2026-06-16",
    cliente_nombre: "Nicolás Herrera",
    cliente_telefono: "+54 11 6233-4455",
    cliente_email: "nicolas.herrera@email.com",
    cliente_documento: "30111777",
    precio_venta: 69800,
    moneda: "USD",
    metodo_pago: "dolares",
    estado: "registrada",
    monto_permuta: null,
    created_at: "2026-06-16T09:45:00.000Z",
    vehiculo: mockVehiculos[2],
    vendedor: {
      id: mockEmpleado.id,
      nombre: mockEmpleado.nombre,
      email: mockEmpleado.email,
      rol: mockEmpleado.rol,
    },
  },
  {
    id: "venta_4",
    vehiculo_id: "veh_5",
    vendedor_id: mockEmpleado.id,
    fecha_venta: "2026-06-12",
    cliente_nombre: "Lucía Soria",
    cliente_telefono: "+54 11 3000-8899",
    cliente_email: "lucia.soria@email.com",
    cliente_documento: "29555111",
    precio_venta: 104500000,
    moneda: "ARS",
    metodo_pago: "pesos",
    estado: "anulada",
    monto_permuta: null,
    created_at: "2026-06-12T15:30:00.000Z",
    vehiculo: mockVehiculos[4],
    vendedor: {
      id: mockEmpleado.id,
      nombre: mockEmpleado.nombre,
      email: mockEmpleado.email,
      rol: mockEmpleado.rol,
    },
  },
  {
    id: "venta_5",
    vehiculo_id: "veh_4",
    vendedor_id: mockEmpleado.id,
    fecha_venta: "2026-06-22",
    cliente_nombre: "Agustina Pérez",
    cliente_telefono: "+54 11 6677-2233",
    cliente_email: "agustina.perez@email.com",
    cliente_documento: "34888999",
    precio_venta: 124900,
    moneda: "USD",
    metodo_pago: "permuta",
    estado: "registrada",
    monto_permuta: 52000,
    created_at: "2026-06-22T12:00:00.000Z",
    vehiculo: mockVehiculos[3],
    vendedor: {
      id: mockEmpleado.id,
      nombre: mockEmpleado.nombre,
      email: mockEmpleado.email,
      rol: mockEmpleado.rol,
    },
  },
];

export const mockProveedores = [
  {
    id: "prov_1",
    nombre: "Gestoría Norte",
    categoria: "gestoria",
    telefono: "+54 9 11 4000-1001",
    activo: true,
  },
  {
    id: "prov_2",
    nombre: "Transporte Premium S.A.",
    categoria: "logistica",
    telefono: "+54 9 11 4000-1002",
    activo: true,
  },
  {
    id: "prov_3",
    nombre: "Lavadero Central",
    categoria: "servicios",
    telefono: "+54 9 11 4000-1003",
    activo: true,
  },
  {
    id: "prov_4",
    nombre: "Patagonia Repuestos",
    categoria: "repuestos",
    telefono: "+54 9 11 4000-1004",
    activo: true,
  },
];

export const mockActivos = [
  {
    id: "act_1",
    tipo: "vehiculo",
    nombre: "BMW X1",
    activo: true,
  },
  {
    id: "act_2",
    tipo: "propiedad",
    nombre: "Local Centro",
    activo: true,
  },
  {
    id: "act_3",
    tipo: "mueble",
    nombre: "Mobiliario oficina",
    activo: true,
  },
  {
    id: "act_4",
    tipo: "herramienta",
    nombre: "Scanner diagnóstico",
    activo: true,
  },
];

export const mockCajaMovimientos = [
  {
    id: "caja_1",
    tipo: "ingreso",
    origen: "venta",
    venta_id: "venta_1",
    venta_pago_id: "vpago_1",
    monto: 94500,
    moneda: "USD",
    fecha: "2026-07-02",
    detalle_1: "Bruno Fernández · Porsche Macan",
    medio: "transferencia",
    detalle_2: "Transferencia",
    detalle_3: "AE123PQ",
    concepto: "Venta de vehículo",
    observaciones: "Ingreso asociado a una venta registrada.",
    created_at: "2026-07-02T11:30:00.000Z",
    proveedor: null,
    activo: {
      id: "act_1",
      tipo: "vehiculo",
      nombre: "BMW X1",
    },
  },
  {
    id: "caja_2",
    tipo: "egreso",
    origen: "compra",
    monto: 480000,
    moneda: "ARS",
    fecha: "2026-07-03",
    detalle_1: "Gestoría patentamiento",
    detalle_2: "Pago parcial",
    detalle_3: "Trámite DNRPA",
    observaciones: "Pago a gestoría de una unidad recién ingresada.",
    created_at: "2026-07-03T09:10:00.000Z",
    proveedor: mockProveedores[0],
    activo: {
      id: "act_2",
      tipo: "propiedad",
      nombre: "Local Centro",
    },
  },
  {
    id: "caja_3",
    tipo: "ingreso",
    origen: "manual",
    monto: 18500,
    moneda: "USD",
    fecha: "2026-07-04",
    detalle_1: "Venta accesorio premium",
    detalle_2: "Cobro en dólares",
    detalle_3: "Caja chica USD",
    observaciones: "Movimiento chico para caja operativa.",
    created_at: "2026-07-04T13:45:00.000Z",
    proveedor: null,
    activo: {
      id: "act_3",
      tipo: "mueble",
      nombre: "Mobiliario oficina",
    },
  },
  {
    id: "caja_4",
    tipo: "egreso",
    origen: "compra",
    monto: 3200,
    moneda: "USD",
    fecha: "2026-07-05",
    detalle_1: "Flete unidad consignada",
    detalle_2: "Pago de transporte",
    detalle_3: "Entregas interurbanas",
    observaciones: "Salida asociada a una entrega especial.",
    created_at: "2026-07-05T08:20:00.000Z",
    proveedor: mockProveedores[1],
    activo: {
      id: "act_4",
      tipo: "herramienta",
      nombre: "Scanner diagnóstico",
    },
  },
  {
    id: "caja_5",
    tipo: "ingreso",
    origen: "venta",
    venta_id: "venta_2",
    venta_pago_id: "vpago_2",
    monto: 73500000,
    moneda: "ARS",
    fecha: "2026-07-06",
    detalle_1: "Sofía Benítez · BMW X3",
    medio: "efectivo",
    detalle_2: "Efectivo",
    detalle_3: "AE456ST",
    concepto: "Venta de vehículo",
    observaciones: "Ingreso principal del día asociado a una venta.",
    created_at: "2026-07-06T12:05:00.000Z",
    proveedor: null,
    activo: {
      id: "act_1",
      tipo: "vehiculo",
      nombre: "BMW X1",
    },
  },
  {
    id: "caja_6",
    tipo: "egreso",
    origen: "ajuste",
    monto: 215000,
    moneda: "ARS",
    fecha: "2026-07-06",
    detalle_1: "Lavadero y estética",
    detalle_2: "Preparación de entrega",
    detalle_3: "Unidad premium",
    observaciones: "Puesta a punto de un vehículo en stock.",
    created_at: "2026-07-06T16:40:00.000Z",
    proveedor: mockProveedores[2],
    activo: {
      id: "act_3",
      tipo: "mueble",
      nombre: "Mobiliario oficina",
    },
  },
  {
    id: "caja_7",
    tipo: "egreso",
    origen: "compra",
    compra_id: "compra_2",
    monto: 60200000,
    moneda: "ARS",
    fecha: "2026-05-02",
    detalle_1: "BMW X3 · AE456ST",
    medio: "transferencia",
    detalle_2: "Proveedor Premium Cars · concesionaria",
    detalle_3: "OP-2026-002",
    concepto: "Compra de vehículo",
    cuenta: "banco_santander",
    observaciones: "Pago parcial asociado a una compra con deuda pendiente.",
    created_at: "2026-05-02T15:45:00.000Z",
    proveedor: mockProveedores[1],
    activo: null,
    compra: {
      id: "compra_2",
      nro_operacion: "OP-2026-002",
      fecha: "2026-05-02",
      vehiculo: {
        id: mockVehiculos[1].id,
        marca: "BMW",
        modelo: "X3",
        dominio: "AE456ST",
      },
      proveedor: {
        id: mockProveedores[1].id,
        nombre: mockProveedores[1].nombre,
      },
    },
  },
  {
    id: "caja_8",
    tipo: "egreso",
    origen: "comision",
    comision_liquidacion_id: "liq_1",
    monto: 2835,
    moneda: "USD",
    fecha: "2026-06-25",
    detalle_1: "Lucas Ríos",
    medio: "transferencia",
    detalle_2: "06/2026",
    detalle_3: "Comisión vendedores",
    concepto: "Pago de comisión",
    cuenta: "banco_santander",
    observaciones: "Pago automático de liquidación.",
    created_at: "2026-06-25T10:00:00.000Z",
    proveedor: null,
    activo: null,
  },
];

const mockVendedorLucas = {
  id: "emp_lucas",
  nombre: "Lucas Ríos",
  email: "lucas@funesexclusivos.com",
  rol: "vendedor",
};

const mockVendedoraAgustina = {
  id: "emp_agustina",
  nombre: "Agustina Pérez",
  email: "agustina@funesexclusivos.com",
  rol: "vendedora",
};

const mockVendedorMartin = {
  id: "emp_martin",
  nombre: "Martín Roldán",
  email: "martin@funesexclusivos.com",
  rol: "vendedor",
};

const mockVendedoraSofia = {
  id: "emp_sofia",
  nombre: "Sofía Benítez",
  email: "sofia@funesexclusivos.com",
  rol: "vendedora",
};

export const mockComisiones = [
  {
    id: "com_1",
    venta_id: "venta_1",
    vendedor_id: mockVendedorLucas.id,
    base_comision: 94500,
    porcentaje: 3,
    monto_comision: 2835,
    moneda: "USD",
    estado: "pagada",
    fecha_generada: "2026-06-20",
    fecha_pago: "2026-06-25",
    observaciones: "Comisión pagada en el cierre semanal.",
    created_at: "2026-06-20T14:20:00.000Z",
    vendedor: mockVendedorLucas,
    venta: {
      id: "venta_1",
      fecha_venta: "2026-06-20",
      cliente_nombre: "Bruno Fernández",
      precio_venta: 94500,
      moneda: "USD",
      metodo_pago: "transferencia",
      estado: "registrada",
      vehiculo: {
        id: "veh_1",
        marca: "Porsche",
        modelo: "Macan",
        version: "S 2.9 V6",
        anio: 2022,
        dominio: "AE123PQ",
      },
    },
  },
  {
    id: "com_2",
    venta_id: "venta_2",
    vendedor_id: mockVendedoraAgustina.id,
    base_comision: 73500000,
    porcentaje: 2.5,
    monto_comision: 1837500,
    moneda: "ARS",
    estado: "aprobada",
    fecha_generada: "2026-06-18",
    fecha_pago: null,
    observaciones: "Aprobada para pago en próximo corte.",
    created_at: "2026-06-18T11:15:00.000Z",
    vendedor: mockVendedoraAgustina,
    venta: {
      id: "venta_2",
      fecha_venta: "2026-06-18",
      cliente_nombre: "Sofía Benítez",
      precio_venta: 73500000,
      moneda: "ARS",
      metodo_pago: "efectivo",
      estado: "registrada",
      vehiculo: {
        id: "veh_2",
        marca: "BMW",
        modelo: "X3",
        version: "xDrive30i",
        anio: 2021,
        dominio: "AE456ST",
      },
    },
  },
  {
    id: "com_3",
    venta_id: "venta_3",
    vendedor_id: mockVendedorMartin.id,
    base_comision: 69800,
    porcentaje: 3.25,
    monto_comision: 2269.5,
    moneda: "USD",
    estado: "pendiente",
    fecha_generada: "2026-06-16",
    fecha_pago: null,
    observaciones: "Pendiente de validación administrativa.",
    created_at: "2026-06-16T10:00:00.000Z",
    vendedor: mockVendedorMartin,
    venta: {
      id: "venta_3",
      fecha_venta: "2026-06-16",
      cliente_nombre: "Nicolás Herrera",
      precio_venta: 69800,
      moneda: "USD",
      metodo_pago: "dolares",
      estado: "registrada",
      vehiculo: {
        id: "veh_3",
        marca: "Audi",
        modelo: "Q5",
        version: "45 TFSI",
        anio: 2020,
        dominio: "AF789UV",
      },
    },
  },
  {
    id: "com_4",
    venta_id: "venta_5",
    vendedor_id: mockVendedoraSofia.id,
    base_comision: 124900,
    porcentaje: 2.8,
    monto_comision: 3497.2,
    moneda: "USD",
    estado: "anulada",
    fecha_generada: "2026-06-22",
    fecha_pago: null,
    observaciones: "Se anuló junto con la operación original.",
    created_at: "2026-06-22T12:10:00.000Z",
    vendedor: mockVendedoraSofia,
    venta: {
      id: "venta_5",
      fecha_venta: "2026-06-22",
      cliente_nombre: "Agustina Pérez",
      precio_venta: 124900,
      moneda: "USD",
      metodo_pago: "permuta",
      estado: "registrada",
      vehiculo: {
        id: "veh_4",
        marca: "Land Rover",
        modelo: "Range Rover Evoque",
        version: "P250 R-Dynamic",
        anio: 2023,
        dominio: "AG112JK",
      },
    },
  },
  {
    id: "com_5",
    venta_id: "venta_4",
    vendedor_id: mockVendedorLucas.id,
    base_comision: 104500000,
    porcentaje: 2.2,
    monto_comision: 2299000,
    moneda: "ARS",
    estado: "pagada",
    fecha_generada: "2026-06-12",
    fecha_pago: "2026-06-15",
    observaciones: "Pago realizado por transferencia.",
    created_at: "2026-06-12T15:35:00.000Z",
    vendedor: mockVendedorLucas,
    venta: {
      id: "venta_4",
      fecha_venta: "2026-06-12",
      cliente_nombre: "Lucía Soria",
      precio_venta: 104500000,
      moneda: "ARS",
      metodo_pago: "pesos",
      estado: "anulada",
      vehiculo: {
        id: "veh_5",
        marca: "Mercedes-Benz",
        modelo: "GLC 300",
        version: "4MATIC Coupe",
        anio: 2022,
        dominio: "AG334LM",
      },
    },
  },
  {
    id: "com_6",
    venta_id: "venta_6",
    vendedor_id: mockVendedoraAgustina.id,
    base_comision: 84900,
    porcentaje: 1.5,
    monto_comision: 1273.5,
    moneda: "USD",
    estado: "aprobada",
    fecha_generada: "2026-06-08",
    fecha_pago: null,
    observaciones: "Comisión de refuerzo por operación cross-sell.",
    created_at: "2026-06-08T13:10:00.000Z",
    vendedor: mockVendedoraAgustina,
    venta: {
      id: "venta_6",
      fecha_venta: "2026-06-08",
      cliente_nombre: "Bruno Fernández",
      precio_venta: 84900,
      moneda: "USD",
      metodo_pago: "transferencia",
      estado: "registrada",
      vehiculo: {
        id: "veh_7",
        marca: "Volvo",
        modelo: "XC60",
        version: "B5 Plus",
        anio: 2024,
        dominio: "AI778QR",
      },
    },
  },
];

export const mockPipelineEstados = [
  { id: "crm_1", slug: "nuevo", nombre: "Nuevo", orden: 1, activo: true },
  { id: "crm_2", slug: "contactado", nombre: "Contactado", orden: 2, activo: true },
  { id: "crm_3", slug: "interesado", nombre: "Interesado", orden: 3, activo: true },
  { id: "crm_4", slug: "negociacion", nombre: "Negociación", orden: 4, activo: true },
  { id: "crm_5", slug: "reservado", nombre: "Reservado", orden: 5, activo: true },
  { id: "crm_6", slug: "ganado", nombre: "Ganado", orden: 6, activo: true },
  { id: "crm_7", slug: "perdido", nombre: "Perdido", orden: 7, activo: true },
];

const mockLeadVendedorLucas = {
  id: "emp_lucas",
  nombre: "Lucas Ríos",
  email: "lucas@funesexclusivos.com",
  rol: "vendedor",
};

const mockLeadVendedoraAgustina = {
  id: "emp_agustina",
  nombre: "Agustina Pérez",
  email: "agustina@funesexclusivos.com",
  rol: "vendedora",
};

const mockLeadVendedorMartin = {
  id: "emp_martin",
  nombre: "Martín Roldán",
  email: "martin@funesexclusivos.com",
  rol: "vendedor",
};

const mockLeadVendedoraSofia = {
  id: "emp_sofia",
  nombre: "Sofía Benítez",
  email: "sofia@funesexclusivos.com",
  rol: "vendedora",
};

export const mockGestoriaResponsables = [
  mockLeadVendedorLucas,
  mockLeadVendedoraAgustina,
  mockLeadVendedorMartin,
  mockLeadVendedoraSofia,
];

export const mockLeads = [
  {
    id: "lead_1",
    nombre: "Bruno Fernández",
    telefono: "+54 11 4111-2233",
    email: "bruno.fernandez@email.com",
    documento: "30111222",
    origen: "whatsapp",
    estado: "ganado",
    presupuesto_min: 78000,
    presupuesto_max: 86000,
    presupuesto_moneda: "USD",
    nivel_interes: 5,
    proximo_contacto: null,
    notas: "Pidió evaluar SUV premium y tomar usado en parte de pago.",
    venta_id: "venta_1",
    fecha_ganado: "2026-06-20",
    created_at: "2026-07-04T10:20:00.000Z",
    vehiculo: {
      id: "veh_7",
      marca: "Volvo",
      modelo: "XC60",
      version: "B5 Plus",
      anio: 2024,
      dominio: "AI778QR",
    },
    vendedor: mockLeadVendedorLucas,
  },
  {
    id: "lead_2",
    nombre: "Micaela López",
    telefono: "+54 11 5222-7788",
    email: "micaela.lopez@email.com",
    documento: "29555999",
    origen: "instagram",
    estado: "interesado",
    presupuesto_min: 65000000,
    presupuesto_max: 78000000,
    presupuesto_moneda: "ARS",
    nivel_interes: 4,
    proximo_contacto: "2026-07-08",
    notas: "Consultó por BMW X3 y agendó seguimiento por video.",
    created_at: "2026-07-03T16:45:00.000Z",
    vehiculo: {
      id: "veh_2",
      marca: "BMW",
      modelo: "X3",
      version: "xDrive30i",
      anio: 2021,
      dominio: "AE456ST",
    },
    vendedor: mockLeadVendedoraAgustina,
  },
  {
    id: "lead_3",
    nombre: "Tomás Gallo",
    telefono: "+54 11 3888-1122",
    email: "tomas.gallo@email.com",
    documento: "28333777",
    origen: "referido",
    estado: "contactado",
    presupuesto_min: 52000,
    presupuesto_max: 62000,
    presupuesto_moneda: "USD",
    nivel_interes: 3,
    proximo_contacto: null,
    notas: "Referido de cliente histórico, busca entrega rápida.",
    created_at: "2026-07-02T09:10:00.000Z",
    vehiculo: {
      id: "veh_3",
      marca: "Audi",
      modelo: "Q5",
      version: "45 TFSI",
      anio: 2020,
      dominio: "AF789UV",
    },
    vendedor: mockLeadVendedorMartin,
  },
  {
    id: "lead_4",
    nombre: "Julieta Rivas",
    telefono: "+54 11 6777-3344",
    email: "julieta.rivas@email.com",
    documento: "30999111",
    origen: "web",
    estado: "nuevo",
    presupuesto_min: 95000,
    presupuesto_max: 120000,
    presupuesto_moneda: "USD",
    nivel_interes: 2,
    proximo_contacto: "2026-07-09",
    notas: "Dejó consulta web por Land Rover o Porsche.",
    created_at: "2026-07-06T11:05:00.000Z",
    vehiculo: null,
    vendedor: mockLeadVendedoraSofia,
  },
  {
    id: "lead_5",
    nombre: "Santiago Mendez",
    telefono: "+54 11 2999-4455",
    email: "santiago.mendez@email.com",
    documento: "32222888",
    origen: "facebook",
    estado: "reservado",
    presupuesto_min: 79000000,
    presupuesto_max: 85000000,
    presupuesto_moneda: "ARS",
    nivel_interes: 5,
    proximo_contacto: "2026-07-07",
    notas: "Reserva condicional hasta cerrar financiamiento.",
    created_at: "2026-07-01T15:30:00.000Z",
    vehiculo: {
      id: "veh_8",
      marca: "Toyota",
      modelo: "SW4",
      version: "SRX 2.8",
      anio: 2023,
      dominio: "AJ990TX",
    },
    vendedor: mockLeadVendedorLucas,
  },
  {
    id: "lead_6",
    nombre: "Carolina Vidal",
    telefono: "+54 11 4555-6677",
    email: "carolina.vidal@email.com",
    documento: "27888999",
    origen: "presencial",
    estado: "perdido",
    presupuesto_min: 104500000,
    presupuesto_max: 104500000,
    presupuesto_moneda: "ARS",
    nivel_interes: 5,
    proximo_contacto: null,
    notas: "Lead perdido por cambio de presupuesto.",
    created_at: "2026-06-28T13:25:00.000Z",
    vehiculo: {
      id: "veh_5",
      marca: "Mercedes-Benz",
      modelo: "GLC 300",
      version: "4MATIC Coupe",
      anio: 2022,
      dominio: "AG334LM",
    },
    vendedor: mockLeadVendedoraAgustina,
  },
];

export const mockLeadInteracciones = [
  {
    id: "li_1",
    lead_id: "lead_1",
    tipo: "llamada",
    titulo: "Llamada inicial",
    contenido: "Se repasan necesidades y se comparte ficha de la unidad.",
    fecha: "2026-07-04T14:00:00.000Z",
    created_at: "2026-07-04T14:00:00.000Z",
    created_by: {
      id: mockLeadVendedorLucas.id,
      nombre: mockLeadVendedorLucas.nombre,
      email: mockLeadVendedorLucas.email,
      rol: mockLeadVendedorLucas.rol,
    },
  },
  {
    id: "li_2",
    lead_id: "lead_1",
    tipo: "mensaje",
    titulo: "Envió de propuesta",
    contenido: "Se envió detalle con precio y condiciones de entrega.",
    fecha: "2026-07-05T10:30:00.000Z",
    created_at: "2026-07-05T10:30:00.000Z",
    created_by: {
      id: mockLeadVendedorLucas.id,
      nombre: mockLeadVendedorLucas.nombre,
      email: mockLeadVendedorLucas.email,
      rol: mockLeadVendedorLucas.rol,
    },
  },
  {
    id: "li_3",
    lead_id: "lead_2",
    tipo: "visita",
    titulo: "Visita al salón",
    contenido: "Vio la unidad en persona y pidió comparar con Q5.",
    fecha: "2026-07-03T18:20:00.000Z",
    created_at: "2026-07-03T18:20:00.000Z",
    created_by: {
      id: mockLeadVendedoraAgustina.id,
      nombre: mockLeadVendedoraAgustina.nombre,
      email: mockLeadVendedoraAgustina.email,
      rol: mockLeadVendedoraAgustina.rol,
    },
  },
  {
    id: "li_4",
    lead_id: "lead_4",
    tipo: "nota",
    titulo: "Consulta web",
    contenido: "Interesada en SUV premium, pidió seguimiento por mail.",
    fecha: "2026-07-06T11:20:00.000Z",
    created_at: "2026-07-06T11:20:00.000Z",
    created_by: {
      id: mockLeadVendedoraSofia.id,
      nombre: mockLeadVendedoraSofia.nombre,
      email: mockLeadVendedoraSofia.email,
      rol: mockLeadVendedoraSofia.rol,
    },
  },
];

export const mockGestoriaTramites = [
  {
    id: "gest_1",
    tipo: "transferencia",
    estado: "pendiente",
    titulo: "Transferencia Porsche Macan",
    descripcion: "Cambio de titularidad y solicitud de cédula azul.",
    cliente_nombre: "Bruno Fernández",
    cliente_telefono: "+54 11 4111-2233",
    cliente_email: "bruno.fernandez@email.com",
    cliente_documento: "30111222",
    fecha_inicio: "2026-07-01",
    fecha_vencimiento: "2026-07-10",
    fecha_finalizacion: null,
    documentos: ["doc_1.pdf", "doc_2.jpg"],
    observaciones: "Esperando documentación completa del comprador.",
    created_at: "2026-07-01T10:20:00.000Z",
    vehiculo: {
      id: "veh_1",
      marca: "Porsche",
      modelo: "Macan",
      version: "S 2.9 V6",
      anio: 2022,
      dominio: "AE123PQ",
    },
    venta: {
      id: "venta_1",
      fecha_venta: "2026-06-20",
      cliente_nombre: "Martín Roldán",
    },
    responsable: mockLeadVendedorLucas,
  },
  {
    id: "gest_2",
    tipo: "cedula",
    estado: "en_proceso",
    titulo: "Cédula y alta de seguro BMW X3",
    descripcion: "Trámite en curso con respaldo de seguro vigente.",
    cliente_nombre: "Sofía Benítez",
    cliente_telefono: "+54 11 4444-7788",
    cliente_email: "sofia.benitez@email.com",
    cliente_documento: "27222333",
    fecha_inicio: "2026-06-25",
    fecha_vencimiento: "2026-07-08",
    fecha_finalizacion: null,
    documentos: ["doc_3.pdf"],
    observaciones: "A la espera de firma digital.",
    created_at: "2026-06-25T12:00:00.000Z",
    vehiculo: {
      id: "veh_2",
      marca: "BMW",
      modelo: "X3",
      version: "xDrive30i",
      anio: 2021,
      dominio: "AE456ST",
    },
    venta: null,
    responsable: mockLeadVendedoraAgustina,
  },
  {
    id: "gest_3",
    tipo: "patente",
    estado: "observado",
    titulo: "Patente SW4 con observación",
    descripcion: "Falta adjuntar certificado de libre deuda.",
    cliente_nombre: "Santiago Mendez",
    cliente_telefono: "+54 11 2999-4455",
    cliente_email: "santiago.mendez@email.com",
    cliente_documento: "32222888",
    fecha_inicio: "2026-06-20",
    fecha_vencimiento: "2026-07-04",
    fecha_finalizacion: null,
    documentos: ["doc_4.png", "doc_5.pdf", "doc_6.pdf"],
    observaciones: "Observado por documentación incompleta.",
    created_at: "2026-06-20T09:45:00.000Z",
    vehiculo: {
      id: "veh_8",
      marca: "Toyota",
      modelo: "SW4",
      version: "SRX 2.8",
      anio: 2023,
      dominio: "AJ990TX",
    },
    venta: null,
    responsable: mockLeadVendedorMartin,
  },
  {
    id: "gest_4",
    tipo: "verificacion_policial",
    estado: "completado",
    titulo: "Verificación policial GLC 300",
    descripcion: "Gestión finalizada y archivada.",
    cliente_nombre: "Lucía Soria",
    cliente_telefono: "+54 11 3000-8899",
    cliente_email: "lucia.soria@email.com",
    cliente_documento: "29555111",
    fecha_inicio: "2026-06-10",
    fecha_vencimiento: "2026-06-18",
    fecha_finalizacion: "2026-06-16",
    documentos: ["doc_7.pdf"],
    observaciones: "Cerrado sin observaciones.",
    created_at: "2026-06-10T08:20:00.000Z",
    vehiculo: {
      id: "veh_5",
      marca: "Mercedes-Benz",
      modelo: "GLC 300",
      version: "4MATIC Coupe",
      anio: 2022,
      dominio: "AG334LM",
    },
    venta: {
      id: "venta_4",
      fecha_venta: "2026-06-12",
      cliente_nombre: "Lucía Soria",
    },
    responsable: mockLeadVendedoraSofia,
  },
  {
    id: "gest_5",
    tipo: "titulo",
    estado: "cancelado",
    titulo: "Título de dominio Evoque",
    descripcion: "Operación cancelada por desistimiento del cliente.",
    cliente_nombre: "Julieta Rivas",
    cliente_telefono: "+54 11 6777-3344",
    cliente_email: "julieta.rivas@email.com",
    cliente_documento: "30999111",
    fecha_inicio: "2026-05-30",
    fecha_vencimiento: "2026-06-07",
    fecha_finalizacion: "2026-06-02",
    documentos: ["doc_8.pdf", "doc_9.jpg"],
    observaciones: "Se archivó sin continuar.",
    created_at: "2026-05-30T16:30:00.000Z",
    vehiculo: {
      id: "veh_4",
      marca: "Land Rover",
      modelo: "Range Rover Evoque",
      version: "P250 R-Dynamic",
      anio: 2023,
      dominio: "AG112JK",
    },
    venta: null,
    responsable: mockLeadVendedorLucas,
  },
  {
    id: "gest_6",
    tipo: "seguro",
    estado: "pendiente",
    titulo: "Seguro inicial XC60",
    descripcion: "Gestión de póliza inicial y cobertura total.",
    cliente_nombre: "Bruno Fernández",
    cliente_telefono: "+54 11 4111-2233",
    cliente_email: "bruno.fernandez@email.com",
    cliente_documento: "30111222",
    fecha_inicio: "2026-07-06",
    fecha_vencimiento: "2026-07-12",
    fecha_finalizacion: null,
    documentos: [],
    observaciones: "Pendiente de cotización de aseguradora.",
    created_at: "2026-07-06T12:10:00.000Z",
    vehiculo: {
      id: "veh_7",
      marca: "Volvo",
      modelo: "XC60",
      version: "B5 Plus",
      anio: 2024,
      dominio: "AI778QR",
    },
    venta: null,
    responsable: mockLeadVendedoraAgustina,
  },
];

export const mockWhatsappInstancias = [
  {
    id: "wapp_1",
    empleado_id: mockLeadVendedorLucas.id,
    provider: "evolution",
    instance_name: "lucas-rios",
    estado: "conectado",
    telefono_conectado: "+54 9 11 5555-1001",
    nombre_perfil: "Lucas Ríos",
    qr_code: null,
    qr_expires_at: null,
    last_connection_at: "2026-07-06T09:10:00.000Z",
    last_disconnection_at: null,
    last_sync_at: "2026-07-06T17:20:00.000Z",
    last_error: null,
    activo: true,
    created_at: "2026-06-28T09:00:00.000Z",
    empleado: mockLeadVendedorLucas,
  },
  {
    id: "wapp_2",
    empleado_id: mockLeadVendedoraAgustina.id,
    provider: "evolution",
    instance_name: "agustina-perez",
    estado: "qr_pendiente",
    telefono_conectado: null,
    nombre_perfil: null,
    qr_code:
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIQAAACEAQAAAAB3TQf6AAAACXBIWXMAAAsSAAALEgHS3X78AAABH0lEQVR4nO3XsQ3CMBCF4W9Q0m6g2ZzC1p2g2sJp2wB4QzqVg8gQ0b1Y7m0mQbNn3l3o+oJwqQd8m0XHnGQAAAAAAAAAA4G0nQmKzW6m4m3X0m7dQ9b8j6m5xg2+0v5n4rYwZ5N7Q5m7J7q8qv3M4dF1B3b8g0m6gqNQ0b+5pK6m7q8m5m8gJ7eQv7cWQ8t3h3x6b0Qx6m7w0j7X3w8k8uVx6m7m6x1Q7s4f7z5Y7g8c4r8wY4h8M5v8GQAAAAAAAAAAAAD8A3c1B0tYVw+YAAAAAElFTkSuQmCC",
    qr_expires_at: "2026-07-06T18:30:00.000Z",
    last_connection_at: null,
    last_disconnection_at: null,
    last_sync_at: null,
    last_error: null,
    activo: true,
    created_at: "2026-07-05T11:00:00.000Z",
    empleado: mockLeadVendedoraAgustina,
  },
  {
    id: "wapp_3",
    empleado_id: mockLeadVendedorMartin.id,
    provider: "evolution",
    instance_name: "martin-roldan",
    estado: "desconectado",
    telefono_conectado: "+54 9 11 5555-1003",
    nombre_perfil: "Martín Roldán",
    qr_code: null,
    qr_expires_at: null,
    last_connection_at: "2026-07-02T13:20:00.000Z",
    last_disconnection_at: "2026-07-05T20:15:00.000Z",
    last_sync_at: "2026-07-05T20:05:00.000Z",
    last_error: "Sesión caducada en WhatsApp Web",
    activo: true,
    created_at: "2026-06-25T08:50:00.000Z",
    empleado: mockLeadVendedorMartin,
  },
  {
    id: "wapp_4",
    empleado_id: mockLeadVendedoraSofia.id,
    provider: "evolution",
    instance_name: "sofia-benitez",
    estado: "error",
    telefono_conectado: null,
    nombre_perfil: "Sofía Benítez",
    qr_code: null,
    qr_expires_at: null,
    last_connection_at: "2026-07-01T10:00:00.000Z",
    last_disconnection_at: "2026-07-03T09:40:00.000Z",
    last_sync_at: "2026-07-03T09:35:00.000Z",
    last_error: "Webhook de Evolution no responde",
    activo: true,
    created_at: "2026-06-24T10:45:00.000Z",
    empleado: mockLeadVendedoraSofia,
  },
];

export const mockConversaciones = [
  {
    id: "conv_1",
    whatsapp_instancia_id: "wapp_1",
    lead_id: "lead_1",
    vendedor_id: mockLeadVendedorLucas.id,
    vehiculo_interes_id: "veh_7",
    canal: "whatsapp",
    estado: "abierta",
    contacto_nombre: "Bruno Fernández",
    contacto_telefono: "+54 11 4111-2233",
    contacto_numero_normalizado: "541141112233",
    contacto_email: "bruno.fernandez@email.com",
    ultimo_mensaje_at: "2026-07-06T17:05:00.000Z",
    last_message_preview: "Perfecto, avancemos con la reserva mañana.",
    mensajes_count: 12,
    unread_count: 2,
    resumen_ia: "Cliente con intención alta y pedido de seguimiento inmediato.",
    interes_compra: "alto",
    intencion_detectada: "compra_unidad",
    proxima_accion_sugerida: "Enviar resumen de financiación y coordinar llamada.",
    requiere_atencion: true,
    created_at: "2026-07-04T10:25:00.000Z",
    instancia: mockWhatsappInstancias[0],
    lead: mockLeads[0],
    vendedor: mockLeadVendedorLucas,
    vehiculo: mockVehiculos[6],
  },
  {
    id: "conv_2",
    whatsapp_instancia_id: "wapp_2",
    lead_id: "lead_2",
    vendedor_id: mockLeadVendedoraAgustina.id,
    vehiculo_interes_id: "veh_2",
    canal: "whatsapp",
    estado: "en_seguimiento",
    contacto_nombre: "Micaela López",
    contacto_telefono: "+54 11 5222-7788",
    contacto_numero_normalizado: "541152227788",
    contacto_email: "micaela.lopez@email.com",
    ultimo_mensaje_at: "2026-07-06T15:30:00.000Z",
    last_message_preview: "Te paso opciones apenas me confirme el cliente la permuta.",
    mensajes_count: 8,
    unread_count: 0,
    resumen_ia: "Interesada, pidió comparar unidades similares y retomar esta semana.",
    interes_compra: "medio",
    intencion_detectada: "comparacion",
    proxima_accion_sugerida: "Enviar comparativa de equipamiento y beneficios.",
    requiere_atencion: false,
    created_at: "2026-07-03T17:00:00.000Z",
    instancia: mockWhatsappInstancias[1],
    lead: mockLeads[1],
    vendedor: mockLeadVendedoraAgustina,
    vehiculo: mockVehiculos[1],
  },
  {
    id: "conv_3",
    whatsapp_instancia_id: "wapp_3",
    lead_id: null,
    vendedor_id: mockLeadVendedorMartin.id,
    vehiculo_interes_id: "veh_8",
    canal: "whatsapp",
    estado: "cerrada",
    contacto_nombre: "Santiago Mendez",
    contacto_telefono: "+54 11 2999-4455",
    contacto_numero_normalizado: "541129994455",
    contacto_email: "santiago.mendez@email.com",
    ultimo_mensaje_at: "2026-07-05T11:45:00.000Z",
    last_message_preview: "Gracias, ya cerramos por otro lado.",
    mensajes_count: 5,
    unread_count: 0,
    resumen_ia: "Conversación cerrada sin avance comercial.",
    interes_compra: "bajo",
    intencion_detectada: "consulta_general",
    proxima_accion_sugerida: "Ninguna.",
    requiere_atencion: false,
    created_at: "2026-07-02T12:15:00.000Z",
    instancia: mockWhatsappInstancias[2],
    lead: null,
    vendedor: mockLeadVendedorMartin,
    vehiculo: mockVehiculos[7],
  },
  {
    id: "conv_4",
    whatsapp_instancia_id: "wapp_4",
    lead_id: "lead_4",
    vendedor_id: mockLeadVendedoraSofia.id,
    vehiculo_interes_id: null,
    canal: "whatsapp",
    estado: "archivada",
    contacto_nombre: "Julieta Rivas",
    contacto_telefono: "+54 11 6777-3344",
    contacto_numero_normalizado: "541167773344",
    contacto_email: "julieta.rivas@email.com",
    ultimo_mensaje_at: "2026-07-01T09:10:00.000Z",
    last_message_preview: "Gracias por la info, seguimos más adelante.",
    mensajes_count: 3,
    unread_count: 0,
    resumen_ia: "Contacto archivado, sin acción pendiente.",
    interes_compra: "sin_interes",
    intencion_detectada: "seguimiento_futuro",
    proxima_accion_sugerida: "Reactivar si vuelve a consultar.",
    requiere_atencion: false,
    created_at: "2026-06-30T10:10:00.000Z",
    instancia: mockWhatsappInstancias[3],
    lead: mockLeads[3],
    vendedor: mockLeadVendedoraSofia,
    vehiculo: null,
  },
  {
    id: "conv_5",
    whatsapp_instancia_id: "wapp_1",
    lead_id: "lead_5",
    vendedor_id: mockLeadVendedorLucas.id,
    vehiculo_interes_id: "veh_8",
    canal: "whatsapp",
    estado: "abierta",
    contacto_nombre: "Santiago Mendez",
    contacto_telefono: "+54 11 2999-4455",
    contacto_numero_normalizado: "541129994455",
    contacto_email: "santiago.mendez@email.com",
    ultimo_mensaje_at: "2026-07-06T16:20:00.000Z",
    last_message_preview: "¿Podemos coordinar visita mañana?",
    mensajes_count: 9,
    unread_count: 1,
    resumen_ia: "Lead con intención media-alta y consulta sobre unidad puntual.",
    interes_compra: "alto",
    intencion_detectada: "visita_salon",
    proxima_accion_sugerida: "Confirmar horario y reservar atención en salón.",
    requiere_atencion: true,
    created_at: "2026-07-01T09:20:00.000Z",
    instancia: mockWhatsappInstancias[0],
    lead: mockLeads[4],
    vendedor: mockLeadVendedorLucas,
    vehiculo: mockVehiculos[7],
  },
];

export const mockConversacionMensajes = [
  {
    id: "wmsg_1",
    conversacion_id: "conv_1",
    tipo: "texto",
    body: "Hola Bruno, te comparto la ficha de la XC60.",
    from_me: true,
    direction: "outbound",
    sent_at: "2026-07-06T16:30:00.000Z",
    created_at: "2026-07-06T16:30:00.000Z",
    created_by: {
      id: mockLeadVendedorLucas.id,
      nombre: mockLeadVendedorLucas.nombre,
      email: mockLeadVendedorLucas.email,
      rol: mockLeadVendedorLucas.rol,
    },
  },
  {
    id: "wmsg_2",
    conversacion_id: "conv_1",
    tipo: "texto",
    body: "Perfecto, avancemos con la reserva mañana.",
    from_me: false,
    direction: "inbound",
    sent_at: "2026-07-06T17:05:00.000Z",
    created_at: "2026-07-06T17:05:00.000Z",
    created_by: null,
  },
  {
    id: "wmsg_3",
    conversacion_id: "conv_2",
    tipo: "texto",
    body: "Te paso opciones apenas me confirme el cliente la permuta.",
    from_me: true,
    direction: "outbound",
    sent_at: "2026-07-06T15:30:00.000Z",
    created_at: "2026-07-06T15:30:00.000Z",
    created_by: {
      id: mockLeadVendedoraAgustina.id,
      nombre: mockLeadVendedoraAgustina.nombre,
      email: mockLeadVendedoraAgustina.email,
      rol: mockLeadVendedoraAgustina.rol,
    },
  },
  {
    id: "wmsg_4",
    conversacion_id: "conv_3",
    tipo: "texto",
    body: "Gracias, ya cerramos por otro lado.",
    from_me: false,
    direction: "inbound",
    sent_at: "2026-07-05T11:45:00.000Z",
    created_at: "2026-07-05T11:45:00.000Z",
    created_by: null,
  },
  {
    id: "wmsg_5",
    conversacion_id: "conv_5",
    tipo: "texto",
    body: "Hola, ¿podemos coordinar visita mañana?",
    from_me: false,
    direction: "inbound",
    sent_at: "2026-07-06T16:20:00.000Z",
    created_at: "2026-07-06T16:20:00.000Z",
    created_by: null,
  },
  {
    id: "wmsg_6",
    conversacion_id: "conv_5",
    tipo: "texto",
    body: "Sí, te esperamos a las 11 hs.",
    from_me: true,
    direction: "outbound",
    sent_at: "2026-07-06T16:40:00.000Z",
    created_at: "2026-07-06T16:40:00.000Z",
    created_by: {
      id: mockLeadVendedorLucas.id,
      nombre: mockLeadVendedorLucas.nombre,
      email: mockLeadVendedorLucas.email,
      rol: mockLeadVendedorLucas.rol,
    },
  },
];

export const mockComisionLiquidaciones = [
  {
    id: "liq_1",
    vendedor_id: mockVendedorLucas.id,
    periodo: "2026-06",
    estado: "pagada",
    moneda: "USD",
    neto_a_cobrar: 2835,
    fecha_pago: "2026-06-25",
    fecha_cierre: "2026-06-24",
    observaciones: "Liquidación pagada por transferencia.",
    created_at: "2026-06-24T18:00:00.000Z",
    updated_at: "2026-06-25T10:00:00.000Z",
    vendedor: mockVendedorLucas,
  },
  {
    id: "liq_2",
    vendedor_id: mockVendedoraAgustina.id,
    periodo: "2026-06",
    estado: "cerrada",
    moneda: "ARS",
    neto_a_cobrar: 1837500,
    fecha_pago: null,
    fecha_cierre: "2026-06-30",
    observaciones: "Cierre administrativo listo para próxima liquidación.",
    created_at: "2026-06-29T09:30:00.000Z",
    updated_at: "2026-06-30T09:45:00.000Z",
    vendedor: mockVendedoraAgustina,
  },
  {
    id: "liq_3",
    vendedor_id: mockVendedorMartin.id,
    periodo: "2026-07",
    estado: "borrador",
    moneda: "USD",
    neto_a_cobrar: 2269.5,
    fecha_pago: null,
    fecha_cierre: null,
    observaciones: "Borrador con ajustes previos a envío.",
    created_at: "2026-07-06T09:00:00.000Z",
    updated_at: "2026-07-06T09:00:00.000Z",
    vendedor: mockVendedorMartin,
  },
  {
    id: "liq_4",
    vendedor_id: mockVendedoraSofia.id,
    periodo: "2026-06",
    estado: "anulada",
    moneda: "USD",
    neto_a_cobrar: 0,
    fecha_pago: null,
    fecha_cierre: null,
    observaciones: "Anulada por reversa de operación.",
    created_at: "2026-06-22T10:00:00.000Z",
    updated_at: "2026-06-22T10:15:00.000Z",
    vendedor: mockVendedoraSofia,
  },
];

export const mockComisionLiquidacionItems = [
  {
    id: "lii_1",
    liquidacion_id: "liq_1",
    tipo: "monto_comision",
    descripcion: "Comisión venta Porsche Macan",
    monto: 2835,
    moneda: "USD",
    orden: 1,
  },
  {
    id: "lii_2",
    liquidacion_id: "liq_2",
    tipo: "monto_comision",
    descripcion: "Comisión venta BMW X3",
    monto: 1837500,
    moneda: "ARS",
    orden: 1,
  },
  {
    id: "lii_3",
    liquidacion_id: "liq_2",
    tipo: "ajuste",
    descripcion: "Redondeo administrativo",
    monto: 0,
    moneda: "ARS",
    orden: 2,
  },
];

export const mockComisionAjustes = [
  {
    id: "laj_1",
    liquidacion_id: "liq_2",
    tipo: "ajuste",
    concepto: "Redondeo administrativo",
    monto: 0,
    moneda: "ARS",
    observaciones: "Ajuste sin impacto monetario.",
  },
];

const mockMediosCaja = [
  "efectivo",
  "banco_santander",
  "cheques_terceros",
  "dolares",
  "car_france",
  "renault_credit",
  "kyoto",
  "metz",
  "avec",
  "mg",
  "cta_hab_sol",
  "otro",
];

mockVehiculos.forEach((vehiculo, index) => {
  const provider = mockProveedores[index % mockProveedores.length];
  Object.assign(vehiculo, {
    motor: index % 2 === 0 ? "2.0 TSI" : "V6 3.0",
    ubicacion: index % 3 === 0 ? "Showroom" : index % 3 === 1 ? "Base" : "Depósito",
    nro_operacion: `OP-2026-${String(index + 1).padStart(3, "0")}`,
    proveedor_id: provider.id,
    fecha_compra: `2026-06-${String(10 + index).padStart(2, "0")}`,
    precio_infoauto_compra: vehiculo.precio_venta ? Math.round(vehiculo.precio_venta * 0.92) : null,
    precio_infoauto_actual: vehiculo.precio_venta ? Math.round(vehiculo.precio_venta * 1.03) : null,
    precio_infoauto_anterior: vehiculo.precio_venta ? Math.round(vehiculo.precio_venta * 0.99) : null,
    precio_permuta: vehiculo.precio_venta ? Math.round(vehiculo.precio_venta * 0.97) : null,
    precio_contado: vehiculo.precio_venta,
    costo_reposicion: vehiculo.costo_adquisicion ? Math.round(vehiculo.costo_adquisicion * 1.08) : null,
    estado_preparacion: index % 3 === 0 ? "pendiente" : index % 3 === 1 ? "en proceso" : "listo",
    chapero: index % 2 === 0 ? "Taller Norte" : "Detailing Centro",
    preparacion_comentarios: index % 2 === 0 ? "Control de entrega y estética" : "Repaso final de interior y exterior",
    publicado_mercadolibre: index % 2 === 0,
    publicado_rodados_google: index % 3 !== 0,
  });
});

mockVentas.forEach((venta, index) => {
  const sale = venta as Record<string, any>;
  Object.assign(sale, {
    precio_infoauto: venta.precio_venta,
    info_historica_compra: venta.precio_venta ? Math.round(venta.precio_venta * 0.88) : null,
    costo_reposicion: venta.precio_venta ? Math.round(venta.precio_venta * 0.9) : null,
    costo_historico: venta.precio_venta ? Math.round(venta.precio_venta * 0.85) : null,
    margen_reposicion: venta.precio_venta ? Math.round(venta.precio_venta * 0.12) : null,
    margen_historico: venta.precio_venta ? Math.round(venta.precio_venta * 0.15) : null,
    rotacion_dias: 18 + index * 4,
    saldo_preventa: venta.precio_venta ? Math.round(venta.precio_venta * 0.4) : null,
    saldo_efectivo: venta.precio_venta ? Math.round(venta.precio_venta * 0.6) : null,
    importe_gestoria: venta.moneda === "USD" ? 450 : 450000,
    importe_escribania: venta.moneda === "USD" ? 380 : 380000,
    resultado_operativo: venta.precio_venta ? Math.round(venta.precio_venta * 0.1) : null,
    pagos: [
      { medio: "efectivo", importe: venta.precio_venta ? Math.round(venta.precio_venta * 0.35) : 0, moneda: venta.moneda },
      { medio: "usado", importe: venta.precio_venta ? Math.round(venta.precio_venta * 0.25) : 0, moneda: venta.moneda },
      { medio: "credito", importe: venta.precio_venta ? Math.round(venta.precio_venta * 0.25) : 0, moneda: venta.moneda },
      { medio: "sena", importe: venta.precio_venta ? Math.round(venta.precio_venta * 0.15) : 0, moneda: venta.moneda },
    ].filter((item) => item.importe > 0),
    entrega: {
      id: `ent_${venta.id}`,
      venta_id: venta.id,
      estado: index % 3 === 0 ? "pendiente" : index % 3 === 1 ? "entregada" : "observada",
      created_at: venta.created_at,
    },
  });
});

{
  const venta0 = mockVentas[0] as Record<string, any>;
  venta0.resultado_operativo = 12500;
  venta0.rotacion_dias = 21;
}
{
  const venta1 = mockVentas[1] as Record<string, any>;
  venta1.resultado_operativo = -4800000;
  venta1.rotacion_dias = 45;
}
{
  const venta2 = mockVentas[2] as Record<string, any>;
  venta2.costo_historico = null;
  venta2.costo_reposicion = null;
  venta2.margen_historico = null;
  venta2.margen_reposicion = null;
  venta2.resultado_operativo = null;
  venta2.rotacion_dias = null;
}
{
  const venta4 = mockVentas[4] as Record<string, any>;
  venta4.resultado_operativo = 8900;
  venta4.rotacion_dias = 9;
}

mockCajaMovimientos.forEach((movimiento, index) => {
  const movimientoRecord = movimiento as Record<string, any>;

  Object.assign(movimientoRecord, {
    origen: movimientoRecord.origen ?? "manual",
    medio: movimientoRecord.medio ?? mockMediosCaja[index % mockMediosCaja.length],
    concepto:
      movimientoRecord.concepto ??
      (index % 3 === 0
        ? "Cobro operación"
        : index % 3 === 1
          ? "Gasto de vehículo"
          : "Soporte operativo"),
    importe: movimientoRecord.monto,
    periodo: movimientoRecord.periodo ?? (String(movimientoRecord.fecha ?? "").slice(0, 7) || "2026-07"),
    cuenta: movimientoRecord.cuenta ?? mockMediosCaja[(index + 3) % mockMediosCaja.length],
  });

  if (movimientoRecord.origen === "comision") {
    const liquidacion = (mockComisionLiquidaciones as Record<string, any>[]).find(
      (item) => item.id === movimientoRecord.comision_liquidacion_id
    );

    if (liquidacion) {
      movimientoRecord.liquidacion = liquidacion;
    }
  }
});

export const mockVentasPagos = [
  {
    id: "vpago_1",
    venta_id: "venta_1",
    tipo: "transferencia",
    fecha: "2026-06-20",
    importe: 94500,
    moneda: "USD",
    medio: "transferencia",
    detalle: "Cobro total por transferencia.",
  },
  {
    id: "vpago_2",
    venta_id: "venta_2",
    tipo: "efectivo",
    fecha: "2026-06-18",
    importe: 73500000,
    moneda: "ARS",
    medio: "efectivo",
    detalle: "Cobro contado en pesos.",
  },
  {
    id: "vpago_3",
    venta_id: "venta_3",
    tipo: "credito",
    fecha: "2026-06-16",
    importe: 69800,
    moneda: "USD",
    medio: "credito",
    detalle: "Operación financiada.",
  },
  {
    id: "vpago_4",
    venta_id: "venta_4",
    tipo: "transferencia",
    fecha: "2026-06-12",
    importe: 104500000,
    moneda: "ARS",
    medio: "transferencia",
    detalle: "Cobro vinculado a la operación anulada.",
  },
  {
    id: "vpago_5a",
    venta_id: "venta_5",
    tipo: "sena",
    fecha: "2026-06-22",
    importe: 15000,
    moneda: "USD",
    medio: "sena",
    detalle: "Seña inicial.",
  },
  {
    id: "vpago_5b",
    venta_id: "venta_5",
    tipo: "efectivo",
    fecha: "2026-06-22",
    importe: 50000,
    moneda: "USD",
    medio: "efectivo",
    detalle: "Cobro en efectivo.",
  },
  {
    id: "vpago_5c",
    venta_id: "venta_5",
    tipo: "usado",
    fecha: "2026-06-22",
    importe: 45000,
    moneda: "USD",
    medio: "usado",
    detalle: "Entrega de usado recibido.",
  },
  {
    id: "vpago_5d",
    venta_id: "venta_5",
    tipo: "credito",
    fecha: "2026-06-22",
    importe: 14900,
    moneda: "USD",
    medio: "credito",
    detalle: "Saldo financiado.",
  },
];

export const mockVentasEntregas = [
  {
    id: "ventrega_1",
    venta_id: "venta_1",
    estado: "pendiente",
    fecha_entrega: null,
    status_informe_vu: "Pendiente",
    usado_credito: null,
    usado_informe_dominio: null,
    usado_multas: null,
    usado_patentes: null,
    usado_observaciones: null,
    observaciones: "Esperando confirmación de fecha.",
    created_at: "2026-06-20T14:20:00.000Z",
    updated_at: "2026-07-06T09:00:00.000Z",
    venta: {
      ...mockVentas[0],
      vehiculo_recibido: null,
    },
  },
  {
    id: "ventrega_2",
    venta_id: "venta_2",
    estado: "lista_para_entregar",
    fecha_entrega: "2026-07-08",
    status_informe_vu: "OK",
    usado_credito: null,
    usado_informe_dominio: null,
    usado_multas: null,
    usado_patentes: null,
    usado_observaciones: null,
    observaciones: "Unidad lista para retiro en sede.",
    created_at: "2026-06-18T11:30:00.000Z",
    updated_at: "2026-07-06T09:00:00.000Z",
    venta: {
      ...mockVentas[1],
      vehiculo_recibido: null,
    },
  },
  {
    id: "ventrega_3",
    venta_id: "venta_3",
    estado: "observada",
    fecha_entrega: null,
    status_informe_vu: "Observado",
    usado_credito: "En revisión",
    usado_informe_dominio: "Pendiente",
    usado_multas: "Sin novedades",
    usado_patentes: "Pendiente",
    usado_observaciones: "Falta completar documentación del usado recibido.",
    observaciones: "Requiere seguimiento de gestoría del usado.",
    created_at: "2026-06-16T10:10:00.000Z",
    updated_at: "2026-07-06T09:00:00.000Z",
    venta: {
      ...mockVentas[2],
      vehiculo_recibido: mockVehiculos[5],
    },
  },
  {
    id: "ventrega_4",
    venta_id: "venta_4",
    estado: "entregada",
    fecha_entrega: "2026-06-15",
    status_informe_vu: "OK",
    usado_credito: null,
    usado_informe_dominio: null,
    usado_multas: null,
    usado_patentes: null,
    usado_observaciones: null,
    observaciones: "Operación cerrada y entregada.",
    created_at: "2026-06-12T15:35:00.000Z",
    updated_at: "2026-07-06T09:00:00.000Z",
    venta: {
      ...mockVentas[3],
      vehiculo_recibido: null,
    },
  },
  {
    id: "ventrega_5",
    venta_id: "venta_5",
    estado: "en_proceso",
    fecha_entrega: null,
    status_informe_vu: "Pendiente de revisión",
    usado_credito: "A validar",
    usado_informe_dominio: "Pendiente",
    usado_multas: "Pendiente",
    usado_patentes: "Pendiente",
    usado_observaciones: "Usado recibido en permuta, falta documentación final.",
    observaciones: "Coordinar entrega luego de completar informes.",
    created_at: "2026-06-22T12:05:00.000Z",
    updated_at: "2026-07-06T09:00:00.000Z",
    venta: {
      ...mockVentas[4],
      vehiculo_recibido: mockVehiculos[6],
    },
  },
];

export const mockVehiculoGastos = [
  {
    id: "vg_1",
    vehiculo_id: mockVehiculos[0].id,
    tipo: "gestoria",
    monto: 750,
    moneda: "USD",
    fecha: "2026-05-15",
    detalle: "Gestoría y alta inicial.",
  },
  {
    id: "vg_2",
    vehiculo_id: mockVehiculos[0].id,
    tipo: "preparacion",
    monto: 320,
    moneda: "USD",
    fecha: "2026-05-18",
    detalle: "Puesta a punto.",
  },
  {
    id: "vg_3",
    vehiculo_id: mockVehiculos[1].id,
    tipo: "patentamiento",
    monto: 450000,
    moneda: "ARS",
    fecha: "2026-05-05",
    detalle: "Patentamiento y sellado.",
  },
  {
    id: "vg_4",
    vehiculo_id: mockVehiculos[1].id,
    tipo: "preparacion",
    monto: 280,
    moneda: "USD",
    fecha: "2026-05-07",
    detalle: "Lavado y estética express en dólares.",
  },
  {
    id: "vg_5",
    vehiculo_id: mockVehiculos[3].id,
    tipo: "gestoria",
    monto: 1200,
    moneda: "USD",
    fecha: "2026-06-02",
    detalle: "Gestoría de ingreso y boletos.",
  },
  {
    id: "vg_6",
    vehiculo_id: mockVehiculos[4].id,
    tipo: "preparacion",
    monto: 980000,
    moneda: "ARS",
    fecha: "2026-05-28",
    detalle: "Acondicionamiento previo a publicación.",
  },
  {
    id: "vg_7",
    vehiculo_id: mockVehiculos[2].id,
    tipo: "gestoria",
    monto: 180000,
    moneda: "ARS",
    fecha: "2026-05-20",
    detalle: "Transferencia y sellado inicial.",
  },
  {
    id: "vg_8",
    vehiculo_id: mockVehiculos[2].id,
    tipo: "preparacion",
    monto: 220,
    moneda: "USD",
    fecha: "2026-05-22",
    detalle: "Detailing premium y presentación.",
  },
];

export const mockComprasVehiculos = [
  {
    id: "compra_1",
    vehiculo_id: mockVehiculos[0].id,
    proveedor_id: mockProveedores[0].id,
    fecha: "2026-05-14",
    nro_operacion: "OP-2026-001",
    precio_compra: 78000,
    precio_boleto: 0,
    moneda: "USD",
    diferencia_b: 0,
    deuda_pendiente: 0,
    observaciones: "Compra cerrada sin deuda.",
    created_at: "2026-05-14T10:20:00.000Z",
    vehiculo: mockVehiculos[0],
    proveedor: mockProveedores[0],
  },
  {
    id: "compra_2",
    vehiculo_id: mockVehiculos[1].id,
    proveedor_id: mockProveedores[1].id,
    fecha: "2026-05-02",
    nro_operacion: "OP-2026-002",
    precio_compra: 62000000,
    precio_boleto: 350000,
    moneda: "ARS",
    diferencia_b: 1250000,
    deuda_pendiente: 1800000,
    observaciones: "Con deuda pendiente a cancelar al proveedor.",
    created_at: "2026-05-02T12:35:00.000Z",
    vehiculo: mockVehiculos[1],
    proveedor: mockProveedores[1],
  },
  {
    id: "compra_3",
    vehiculo_id: mockVehiculos[3].id,
    proveedor_id: mockProveedores[2].id,
    fecha: "2026-06-01",
    nro_operacion: "OP-2026-003",
    precio_compra: 105000,
    precio_boleto: 2500,
    moneda: "USD",
    diferencia_b: 4200,
    deuda_pendiente: 0,
    observaciones: "Incluye boleto y ajuste por diferencia B.",
    created_at: "2026-06-01T16:15:00.000Z",
    vehiculo: mockVehiculos[3],
    proveedor: mockProveedores[2],
  },
  {
    id: "compra_4",
    vehiculo_id: mockVehiculos[4].id,
    proveedor_id: mockProveedores[3].id,
    fecha: "2026-05-26",
    nro_operacion: "OP-2026-004",
    precio_compra: 89000000,
    precio_boleto: 1200000,
    moneda: "ARS",
    diferencia_b: 2500000,
    deuda_pendiente: 3200000,
    observaciones: "Compra con saldo a regularizar y publicación futura.",
    created_at: "2026-05-26T11:10:00.000Z",
    vehiculo: mockVehiculos[4],
    proveedor: mockProveedores[3],
  },
];

export const mockGestoriaPresupuestos = [
  {
    id: "gp_1",
    tramite_id: mockGestoriaTramites[0].id,
    venta_id: "venta_1",
    vehiculo_id: mockVehiculos[0].id,
    estado: "aprobado",
    cliente_nombre: "Bruno Fernández",
    cliente_telefono: "+54 11 4111-2233",
    cliente_email: "bruno.fernandez@email.com",
    cliente_documento: "30111222",
    fecha: "2026-07-01",
    moneda: "USD",
    valor_vehiculo: 84500,
    valor_tabla_dnrpa: 2500,
    valor_tabla_api: 2400,
    subtotal: 690,
    total: 690,
    link_dnrpa: "https://dnrpa.example/consulta/1",
    link_api: "https://api.example/consulta/1",
    observaciones: "Presupuesto aprobado para transferencia y certificaciones.",
    created_at: "2026-07-01T10:35:00.000Z",
    tramite: mockGestoriaTramites[0],
    venta: mockVentas[0],
    vehiculo: mockVehiculos[0],
  },
  {
    id: "gp_2",
    tramite_id: mockGestoriaTramites[1].id,
    venta_id: "venta_2",
    vehiculo_id: mockVehiculos[1].id,
    estado: "facturado",
    cliente_nombre: "Sofía Benítez",
    cliente_telefono: "+54 11 4444-7788",
    cliente_email: "sofia.benitez@email.com",
    cliente_documento: "27222333",
    fecha: "2026-06-27",
    moneda: "ARS",
    valor_vehiculo: 74500000,
    valor_tabla_dnrpa: 320000,
    valor_tabla_api: 295000,
    subtotal: 1850000,
    total: 1850000,
    link_dnrpa: "https://dnrpa.example/consulta/2",
    link_api: "https://api.example/consulta/2",
    observaciones: "Factura emitida con honorarios y sellado.",
    created_at: "2026-06-27T15:20:00.000Z",
    tramite: mockGestoriaTramites[1],
    venta: mockVentas[1],
    vehiculo: mockVehiculos[1],
  },
  {
    id: "gp_3",
    tramite_id: mockGestoriaTramites[2].id,
    venta_id: "venta_3",
    vehiculo_id: mockVehiculos[2].id,
    estado: "rechazado",
    cliente_nombre: "Santiago Mendez",
    cliente_telefono: "+54 11 2999-4455",
    cliente_email: "santiago.mendez@email.com",
    cliente_documento: "32222888",
    fecha: "2026-06-22",
    moneda: "USD",
    valor_vehiculo: 62000,
    valor_tabla_dnrpa: 2150,
    valor_tabla_api: 2050,
    subtotal: 240,
    total: 240,
    link_dnrpa: "https://dnrpa.example/consulta/3",
    link_api: "https://api.example/consulta/3",
    observaciones: "Rechazado por datos pendientes del usado.",
    created_at: "2026-06-22T12:05:00.000Z",
    tramite: mockGestoriaTramites[2],
    venta: mockVentas[2],
    vehiculo: mockVehiculos[2],
  },
  {
    id: "gp_4",
    tramite_id: null,
    venta_id: "venta_5",
    vehiculo_id: mockVehiculos[4].id,
    estado: "borrador",
    cliente_nombre: "Carla Rivas",
    cliente_telefono: "+54 11 3888-6611",
    cliente_email: "carla.rivas@email.com",
    cliente_documento: "33444555",
    fecha: "2026-07-06",
    moneda: "ARS",
    valor_vehiculo: 98000000,
    valor_tabla_dnrpa: 275000,
    valor_tabla_api: 260000,
    subtotal: 370000,
    total: 370000,
    link_dnrpa: null,
    link_api: null,
    observaciones: "Borrador con estimación preliminar.",
    created_at: "2026-07-06T13:10:00.000Z",
    tramite: null,
    venta: mockVentas[4],
    vehiculo: mockVehiculos[4],
  },
];

export const mockGestoriaPresupuestoItems = [
  {
    id: "gpi_1",
    presupuesto_id: "gp_1",
    tipo: "valor_tabla_dnrpa",
    descripcion: "Consulta DNRPA",
    monto: 180,
    moneda: "USD",
    orden: 1,
  },
  {
    id: "gpi_2",
    presupuesto_id: "gp_1",
    tipo: "certificaciones",
    descripcion: "Certificación de firmas",
    monto: 110,
    moneda: "USD",
    orden: 2,
  },
  {
    id: "gpi_3",
    presupuesto_id: "gp_1",
    tipo: "honorarios",
    descripcion: "Honorarios de gestoría",
    monto: 400,
    moneda: "USD",
    orden: 3,
  },
  {
    id: "gpi_4",
    presupuesto_id: "gp_2",
    tipo: "aranceles",
    descripcion: "Aranceles de transferencia",
    monto: 520000,
    moneda: "ARS",
    orden: 1,
  },
  {
    id: "gpi_5",
    presupuesto_id: "gp_2",
    tipo: "impuesto_sellos",
    descripcion: "Sellado provincial",
    monto: 420000,
    moneda: "ARS",
    orden: 2,
  },
  {
    id: "gpi_6",
    presupuesto_id: "gp_2",
    tipo: "formularios",
    descripcion: "Formularios y certificaciones",
    monto: 185000,
    moneda: "ARS",
    orden: 3,
  },
  {
    id: "gpi_7",
    presupuesto_id: "gp_2",
    tipo: "honorarios",
    descripcion: "Honorarios completos",
    monto: 725000,
    moneda: "ARS",
    orden: 4,
  },
  {
    id: "gpi_8",
    presupuesto_id: "gp_3",
    tipo: "ceta_factura",
    descripcion: "CETA / factura",
    monto: 240,
    moneda: "USD",
    orden: 1,
  },
  {
    id: "gpi_9",
    presupuesto_id: "gp_4",
    tipo: "valor_tabla_api",
    descripcion: "Consulta API",
    monto: 120000,
    moneda: "ARS",
    orden: 1,
  },
  {
    id: "gpi_10",
    presupuesto_id: "gp_4",
    tipo: "registro",
    descripcion: "Registro y presentación",
    monto: 250000,
    moneda: "ARS",
    orden: 2,
  },
];
